spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_adoption_db?verifyServerCertificate=false&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:testdata.sql