package com.john.price.PetAdoption.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.john.price.PetAdoption.Repositories.PetRepository;

@Controller
@RequestMapping(path="/")
public class RootController {

	@Autowired // This means to get the bean called userRepository. Which is auto-generated by Spring, we will use it to handle the data
	private PetRepository petRepository;
	
	@RequestMapping
    public String greeting(Model model) {
        model.addAttribute("pets", (petRepository.findAll()));
        return "home";
    }

}
